# Python for Aerodynamic Performance Group

### Southampton University Formula Student Team | SUFST

This notebook introduces the Python skills required to contribute to the Aerodynamic Performance Group (APG).

The focus is on using Python as an engineering tool for aerodynamic analysis, data processing, visualisation, CFD automation, and optimisation which are the main goals for the 2026/2027 year in apg.

No previous Python experience is required.

## How to Use This Notebook

This notebook is intended to be worked through in order.

For each section:

1. **Read the explanation** to understand the concept being introduced.
2. **Read through the example code** and make sure you understand what each line is doing.
3. **Run the code yourself** and look at the output.
4. **Experiment with the examples.** Change values, add lines, and see what happens.
5. Every few sections, you will reach an **Exercise**. Try to complete these yourself using what you have learned so far.

> Call me or another expereinced member if you need any help, I encourage you not to use ai. AI is very helpfull when writing some code, but it is awful when your goal is to learn the language

The exercises are designed to combine multiple concepts, so avoid immediately looking for a solution if you get stuck. Go back through the previous examples first.

You are encouraged to modify this notebook while learning. You will learn Python much faster by writing and changing code than by simply reading it.

> **You are not expected to memorise everything.** The aim is to understand the fundamentals well enough that you can recognise what you need and know how to find or implement it. You are encouraged to keep this notebook and reference back to it whenever you need help with programming concepts, the concepts can be applied to all languages


---

**Created and maintained by:**
Ibraheem Mukadam
 APG Mentor | 2026/27

for any questions:

email: im2g24@soton.ac.uk

## Section 1: Python Fundamentals

Before using Python for engineering applications, it is important to understand the **fundamentals of the language**.

This section introduces the core concepts used in almost every Python program. These form the foundation for everything we will do later in this notebook.

In this section, we will cover:

- **Variables and data types** for storing information.
- **Mathematical and comparison operators** for working with values.
- **Conditional statements** for making decisions.
- **Loops** for repeating tasks.
- **Lists** for storing multiple values.
- **Functions** for creating reusable sections of code.
- **Classes** for organising related data and functionality.

The aim of this section is not to cover every feature of Python, but to give you the fundamental knowledge needed to understand, write and modify Python code used within Aerodynamic Performance.



### 1. Prints and Variables

The `print()` function displays information in the console.

This can be text, numbers, variables, or the results of calculations.

In [56]:
print("Hello World!")
print(2026)
print(10 + 5)

Hello World!
2026
15


### Variables

Variables allow us to store values under a name so that we can use them later.


In Python, a variable is created by assigning a value using `=`.

In [57]:
velocity = 20
airDensity = 1.225
teamName = "SUFST"

print(velocity)
print(airDensity)
print(teamName)

# you can print multiple things at a time, seperated by a comma they print on one line
print(velocity, airDensity, teamName)

20
1.225
SUFST
20 1.225 SUFST


you can also do maths opperations on your variables

In [58]:
velocity = 20
airDensity = 1.225
referenceArea = 1.5
liftCoefficient = 3.0

# Calculate Downforce of a wing under the above conditions
downforce = 0.5 * airDensity * velocity**2 * referenceArea * liftCoefficient

print(downforce)

1102.5000000000002


### Data Types

Variables can store different types of data. The type determines what kind of value is being stored and what operations can be performed on it.

Some of the most common Python data types are:

- `int` - whole numbers
- `float` - decimal numbers
- `str` - text
- `bool` - either `True` or `False`

Python automatically determines the data type when a value is assigned to a variable, so you do not need to thing about it.

however, not all opperations can be done to every data type, so being aware of data types will stop errors

In [59]:
numberOfRuns = 10          # Integer
velocity = 25.5            # Float
component = "Front Wing"   # String
simulationComplete = True  # Boolean

print(numberOfRuns)
print(velocity)
print(component)
print(simulationComplete)

10
25.5
Front Wing
True


### First, remove the # at the start of line 5

> **Notice:** Different data types support different operations. For example, we cannot subtract strings or make an integer uppercase. Although Python allows some unusual operations between data types, they may not always make logical sense.

after you have studied this cell put a # at the start of line 5 to stop the error so you can continue with the notebook

the # will turn the line into a comment, a comment is there so you as the dev can leave notes. comments are ignored by the computer and any code is not ran

In [60]:
text = "SUFST"
number = 10

print(text.upper())      # Works
#print(number.upper())    # Error

SUFST


### Strings

A **string (`str`)** is a sequence of characters used to store text. Strings are created by placing text inside either single `' '` or double `" "` quotation marks.

Strings have some slightly strange opperations, but mostly they are used for text
more is explained in the comments

In [61]:
# strings can be "concantinated" using the + (in other words, combined together)
firstWord = "Front"
secondWord = "Wing"
component = firstWord + " " + secondWord
print(component)
print()

# different ways to modify the string
print(component.upper())                  # FRONT WING
print(component.lower())                  # front wing
print(component.title())                  # Front Wing
print(component.replace("wing", "aero"))  # front aero

# length of the string
print("length of string: ", len(component))
print()


# F strings are very usefull when printing out variables
downforce = 350.5
velocity = 20

print(f"The {component} produces {downforce} N of downforce.")
print(f"The velocity is {velocity} m/s.")
print(f"The velocity squared is {velocity**2} m²/s².")


Front Wing

FRONT WING
front wing
Front Wing
Front Wing
length of string:  10

The Front Wing produces 350.5 N of downforce.
The velocity is 20 m/s.
The velocity squared is 400 m²/s².


### Integers and Floats

Python has two main data types for storing numbers:

- **Integer (`int`)**: A whole number with no decimal point, such as `5`, `20`, or `-10`.
- **Float (`float`)**: A number containing a decimal point, such as `5.2`, `20.0`, or `-10.5`.

Both integers and floats can be used in mathematical operations.

When an integer and a float are used together in a calculation, the result will generally be a float.

### Type Conversion

We can convert between numerical data types using:

- `int()` to convert a value to an integer.
- `float()` to convert a value to a float.

**Note:** Converting a float to an integer does not round the number. It removes the decimal part.

If we want to round a number instead, we can use `round()`.

In [62]:
# Integers and floats
numberOfSimulations = 20
velocity = 25.5

print("number of simulations ",numberOfSimulations)
print(type(numberOfSimulations))
print()


print(velocity)
print(type(velocity))
print()


# Using ints and floats together
result = numberOfSimulations + velocity

print("result ", result)
print("result type: ", type(result))
print()


# Type conversion
integerVelocity = int(velocity)
floatSimulations = float(numberOfSimulations)

print("int velocity : ", integerVelocity)
print("float simulations, ",floatSimulations)
print()


# int() vs round()
number = 5.7

print("turning number into int :", int(number))
print("vs")
print("using rounding function", round(number))

number of simulations  20
<class 'int'>

25.5
<class 'float'>

result  45.5
result type:  <class 'float'>

int velocity :  25
float simulations,  20.0

turning number into int : 5
vs
using rounding function 6


### Important: Numbers Can Be Strings

A value containing numbers is **not necessarily an integer or float**.

If a value is placed inside quotation marks, Python treats it as a string, regardless of what is inside.

Therefore `"12"` is a string, not the integer `12`

 `"1.24"` is a string, not the float `1.24`.

This is important because strings and numerical values behave differently when used in operations

Numerical strings can be converted into numbers using `int()` or `float()` and a number can be made a string using `str()`.

In [63]:
integerNumber = 12
integerString = "12"

floatNumber = 1.24
floatString = "1.24"

print("integerMumber is of type ", type(integerNumber))
print("integerString is of type",type(integerString))
print()


print("floatNumber is of type",type(floatNumber))
print("floatString is of type",type(floatString))
print()

# Notice the different behaviour
# the numbers dont add correctly
print("integer type addition: ", integerNumber + integerNumber)
print("string type addition: ", integerString + integerString)
print()


# Converting numerical strings
convertedInteger = int(integerString)
convertedFloat = float(floatString)

print(convertedInteger)
print(convertedFloat)

integerMumber is of type  <class 'int'>
integerString is of type <class 'str'>

floatNumber is of type <class 'float'>
floatString is of type <class 'str'>

integer type addition:  24
string type addition:  1212

12
1.24


### Booleans

A **Boolean (`bool`)** is a data type that can have only one of two values:

- `True`
- `False`

Booleans are commonly used to represent whether a condition or statement is true or false.

Unlike strings, `True` and `False` are written **without quotation marks** and must begin with a capital letter.

Booleans become particularly useful when we begin using comparisons and conditional statements in the next section.

In [64]:
simulationComplete = True
carOnTrack = False

print(simulationComplete)
print(carOnTrack)
print()

# These are not the same data type, they are probably even different colours on your screen
booleanValue = True
stringValue = "True"


True
False



### Mathematical Operators

Python can perform mathematical calculations using **operators**.

The main mathematical operators are:

- `+` Addition
- `-` Subtraction
- `*` Multiplication
- `/` Division
- `**` Exponentiation
- `%` Modulus, gives the remainder after division
- `//` Floor division, divides and removes the decimal part

Python follows the normal **order of operations**, so brackets and powers are evaluated before multiplication, division, addition and subtraction.

Mathematical operations can be performed directly on numbers or using values stored in variables.

### Updating Variables

We can also update the value stored in an existing variable.

Python provides shorthand operators for doing this:

- `+=` Add to the current value
- `-=` Subtract from the current value
- `*=` Multiply the current value
- `/=` Divide the current value

In [65]:
# Basic mathematical operators

a = 10
b = 3

print(a + b)     # Addition
print(a - b)     # Subtraction
print(a * b)     # Multiplication
print(a / b)     # Division
print(a ** b)    # Exponentiation
print(a % b)     # Remainder
print(a // b)    # Floor division
print()

# Order of operations

result1 = 2 + 3 * 4
result2 = (2 + 3) * 4

print(result1)
print(result2)
print()


# Using variables in calculations

airDensity = 1.225
velocity = 20
referenceArea = 1.5
liftCoefficient = 2.5

downforce = 0.5 * airDensity * velocity**2 * referenceArea * liftCoefficient

print(downforce)
print()


# Updating variables

numberOfSimulations = 10

numberOfSimulations += 5
print(numberOfSimulations)

numberOfSimulations -= 2
print(numberOfSimulations)

numberOfSimulations *= 2
print(numberOfSimulations)

numberOfSimulations /= 4
print(numberOfSimulations)

13
7
30
3.3333333333333335
1000
1
3

14
20

918.7500000000001

15
13
26
6.5


### Exercise 1: Basic Aero Calculation

You have been given some basic information from a CFD simulation of a Formula Student car.

The simulation was run with:

- Air density of **1.225 kg/m³**
- Velocity of **20 m/s**
- Reference area of **1.5 m²**
- Lift coefficient of **-2.4**
- Drag coefficient of **0.9**
- The simulation has successfully completed

### Your Task

1. Store each of the values above in appropriately named variables.
2. Store whether the simulation has completed using a Boolean.
3. Calculate the **downforce** produced by the car using:

   $Downforce = -½ × ρ × V² × A × CL$

4. Calculate the **drag force** using:

   **Drag = 0.5 × ρ × V² × A × CD**

5. Create a string containing the name `"SUFST CFD Simulation"`.
6. Print the simulation name.
7. Print the calculated downforce and drag force using an F string.
8. Print whether the simulation has completed.

### Extra Challenge

Calculate the aerodynamic efficiency of the car using:

**Aerodynamic Efficiency = Downforce / Drag**

Store the result in a variable and print it.

Try to complete the exercise using only what has been covered so far.

In [66]:
# Write Code here:


### Comparison Operators

Comparison operators are used to compare two values.

The result of a comparison is always a Boolean value, either `True` or `False`.

The main comparison operators are:

- `==` Equal to
- `!=` Not equal to
- `>` Greater than
- `<` Less than
- `>=` Greater than or equal to
- `<=` Less than or equal to

### Important: `=` vs `==`

These have different meanings in Python.

`=` is used to **assign a value** to a variable.

`==` is used to **compare two values** and check whether they are equal.

This is a very common mistake when first learning Python.

Comparisons can be performed directly between values or between variables.

In [67]:
velocity = 20
maximumVelocity = 25

print(velocity > maximumVelocity)
print(velocity < maximumVelocity)

print()

numberOfRuns = 10

print(numberOfRuns == 10)
print(numberOfRuns == 20)

print()

component = "Front Wing"

print(component == "Front Wing")
print(component == "Rear Wing")

False
True
False
True
True
True
True
<class 'bool'>
True
False
True
False


### If, Elif and Else Statements

So far, our code has run from top to bottom and every line has been executed.

Conditional statements allow our program to make **decisions**. We can tell Python to only run certain code when a particular condition is met.

### `if`

An `if` statement checks whether a condition is `True`.

If the condition is `True`, the indented code underneath it is executed. If the condition is `False`, Python skips that code.

### `else`

An `else` statement can be used to specify what should happen when the `if` condition is `False`.

### `elif`

`elif`, meaning **else if**, allows us to check additional conditions.

Python checks the conditions from top to bottom and executes the first one that is `True`.
you can have multiple elif statements to check for many conditions, they are checked in the order you write them, so if the first is true its code is executed and the rest ignored, even if one later down is also true.

### Indentation

Indentation is very important in Python.

The indented code underneath an `if`, `elif`, or `else` statement belongs to that statement. Python usually uses a tab, or 4 spaces for each level of indentation. (it doesnt matter how much you indent as long as ur consistant, in apg we will use one tab/4 spaces)

### Multiple Conditions

Sometimes we want to check more than one condition at once. We can use:

- `and` when **both** conditions must be `True`
- `or` when **at least one** condition must be `True`
- `not` to reverse a Boolean condition

In [68]:
downforce = 450
targetDownforce = 400

# Basic if statement
if downforce > targetDownforce:
    print("Downforce target achieved")

print()


# If and else
if downforce > targetDownforce:
    print("Downforce target achieved")
else:
    print("Downforce target not achieved")

print()


# If, elif and else
if downforce > 500:
    print("High downforce")

elif downforce > 400:
    print("Medium downforce")

elif downforce > 450:
    # TODO tell me why this elif block will not run?
    print("medium high downforce")

else:
    print("Low downforce")

print()


# Multiple conditions using and
downforce = 450
drag = 180

if downforce > 400 and drag < 200:
    print("Aero targets achieved")

print()


# Multiple conditions using or
if downforce < 300 or drag > 250:
    print("Aero performance needs improvement")
else:
    print("Aero performance is acceptable")

print()


# Using not
simulationFailed = False

if not simulationFailed:
    print("Simulation completed successfully")
else:
    print("Simulation failed")

Downforce target achieved
Downforce target achieved
Medium downforce
Aero targets achieved
Simulation completed successfully


### For Loops
> this section is very important for the work we will be doing in apg for cfd sweeps and optimisation

A **loop** allows us to repeat a section of code multiple times without having to write the same code repeatedly.

A `for` loop is used when we want to repeat something a known number of times or work through a collection of values.

### `range()`

The `range()` function generates a sequence of integers that a `for` loop can work through.

For example, `range(5)` generates numbers from `0` to `4`.

Remember that Python starts counting from `0`, and the final value in `range()` is **not included**.

We can also specify a starting value and step size:

- `range(5)` → 0, 1, 2, 3, 4
- `range(2, 6)` → 2, 3, 4, 5
- `range(0, 10, 2)` → 0, 2, 4, 6, 8

Just like with `if` statements, indentation tells Python which code belongs inside the loop.

The variable used in the `for` statement changes value each time the loop repeats. Each repetition of a loop is called an **iteration**.

you can also for loop through a list, a list is just a collection of things, and is a new data type!

In [71]:
# Basic for loop
for i in range(5):
    print(i)

print()


# Choosing a start and end
for i in range(2, 6):
    print(i)

print()


# Choosing a step size
for i in range(0, 10, 2):
    print(i)

print()

# NEW DATA TYPE: LIST
# lists can hold any data type within them
ourList = [0, 1, 2, 3, 4, 5, "exampleString", True, False]
for item in ourList:
    print(item)

# Using the loop variable in a calculation
for velocity in range(10, 31, 5):
    velocitySquared = velocity**2

    print(f"Velocity: {velocity} m/s")
    print(f"Velocity Squared: {velocitySquared} m²/s²")

print()


# Repeating an aerodynamic calculation
# todo, we will be doing this as part of the real apg work, but . . .
# todo . . . in a more complex system using starccm and solidworks
airDensity = 1.225
referenceArea = 1.5
liftCoefficient = -2.4

for velocity in range(10, 31, 5):
    downforce = -0.5 * airDensity * velocity**2 * referenceArea * liftCoefficient

    print(f"At {velocity} m/s, Downforce = {round(downforce, 2)} N")

0
1
2
3
4

2
3
4
5

0
2
4
6
8

0
1
2
3
4
5
exampleString
True
False
Velocity: 10 m/s
Velocity Squared: 100 m²/s²
Velocity: 15 m/s
Velocity Squared: 225 m²/s²
Velocity: 20 m/s
Velocity Squared: 400 m²/s²
Velocity: 25 m/s
Velocity Squared: 625 m²/s²
Velocity: 30 m/s
Velocity Squared: 900 m²/s²

At 10 m/s, Downforce = 220.5 N
At 15 m/s, Downforce = 496.12 N
At 20 m/s, Downforce = 882.0 N
At 25 m/s, Downforce = 1378.12 N
At 30 m/s, Downforce = 1984.5 N


### While Loops

A `while` loop repeatedly runs a section of code **while a condition remains `True`**.

Unlike a `for` loop, a `while` loop does not necessarily run a known number of times. Instead, it continues until its condition becomes `False`.

This makes `while` loops useful when we want something to continue until a particular condition is reached.

The condition is checked before every iteration of the loop.

### Updating the Condition

It is important that something inside the loop eventually causes the condition to become `False`.

If the condition never becomes `False`, the loop will continue forever. This is called an **infinite loop**. if u get an infinite loop u will need to restart your programming softward lol

### For Loop vs While Loop

A `for` loop is generally used when we know what values we want to loop through or how many iterations we want.

A `while` loop is generally used when we want to continue until a particular condition is met.

In [72]:
# Basic while loop
iteration = 0

while iteration < 5:
    print(iteration)
    iteration += 1

print()


# Continue until a target is reached
downforce = 200
targetDownforce = 400

while downforce < targetDownforce:
    print(f"Current Downforce: {downforce} N")
    downforce += 50

print(f"Target reached: {downforce} N")

print()


# Simulation example
iteration = 0
maximumIterations = 5
simulationConverged = False

while iteration < maximumIterations and not simulationConverged:
    iteration += 1

    print(f"Running iteration {iteration}")

    if iteration == 4:
        simulationConverged = True

print()

print(f"Simulation Converged: {simulationConverged}")

0
1
2
3
4

Current Downforce: 200 N
Current Downforce: 250 N
Current Downforce: 300 N
Current Downforce: 350 N
Target reached: 400 N

Running iteration 1
Running iteration 2
Running iteration 3
Running iteration 4

Simulation Converged: True


### Lists

I mentioned these earlier in the for loops section, a **list** allows us to store multiple values inside a single variable.

Lists are created using square brackets `[ ]`, with each item separated by a comma.

A list can contain numbers, strings, Booleans, or even a mixture of different data types.

### Indexing

Each item in a list has an **index**, which represents its position.

Python starts counting from `0`, so the first item has an index of `0`, the second has an index of `1`, and so on.

Negative indices can be used to count backwards from the end of a list. An index of `-1` refers to the final item.

We can use an item's index to access or change it.


### Adding and Removing Items

Python provides several methods for modifying lists.

- `append()` adds an item to the end of a list.
- `insert()` adds an item at a specified index.
- `remove()` removes a specified item.
- `pop()` removes an item at a specified index.

The `len()` function can be used to find the number of items in a list.

### Looping Through Lists

A `for` loop can be used to work through every item in a list.

This is extremely useful when we want to perform the same calculation or operation on multiple values.

In [ ]:
# Creating lists
velocities = [10, 15, 20, 25, 30]

components = ["Front Wing", "Floor", "Rear Wing"]

print(velocities)
print(components)

print()


# Accessing items using their index
# remember, 0 is the first term, this is a very common mistake
print(velocities[0])
print(velocities[2])
print(velocities[-1])

print()


# Changing an item
velocities[1] = 17

print(velocities)

print()


# Adding items
velocities.append(35)
velocities.insert(0, 5)

print(velocities)

print()


# Removing items
velocities.remove(20)

print(velocities)

velocities.pop(0)

print(velocities)

print()


# Finding the length of a list
print(len(velocities))

print()


# Looping through a list
velocities = [10, 15, 20, 25, 30]

for velocity in velocities:
    print(f"Velocity: {velocity} m/s")

print()


# Using a list for an aerodynamic calculation
airDensity = 1.225
referenceArea = 1.5
liftCoefficient = -2.4

# this is a velocity sweep, lets us test various conditions for our solver
for velocity in velocities:
    downforce = -0.5 * airDensity * velocity**2 * referenceArea * liftCoefficient

    print(f"At {velocity} m/s, Downforce = {round(downforce, 2)} N")

### Functions

A **function** is a reusable block of code designed to perform a specific task.

Functions allow us to write a piece of code once and then use it multiple times throughout a program. This helps make code shorter, easier to understand, and easier to modify.

Functions are created using the `def` keyword followed by the function name and brackets.

### Parameters and Arguments

Functions can be given information to work with.

A **parameter** is a variable defined when the function is created.

An **argument** is the actual value given to the function when it is called.

A function can have multiple parameters, separated by commas.

### Default Parameters

A parameter can be given a **default value** when a function is defined. If no argument is provided when the function is called, Python will use the default value instead.

### Returning Values

A function can use `return` to send a result back to the part of the program that called it.

The returned value can then be stored in a variable, printed, or used in another calculation.

Functions are particularly useful for engineering calculations because the same calculation can be reused with many different inputs.

### Docstrings
A **docstring** is a short description placed inside a function to explain what the function does, its inputs, and what it returns. you should get in the habbit of writing these, when code gets big its very easy to forget what it does



In [ ]:
# Function with a parameter
def PrintVelocity(velocity):
    print(f"Velocity: {velocity} m/s")

PrintVelocity(20)
PrintVelocity(25)

print()


# Function with multiple parameters and a return value
def CalculateDownforce(airDensity, velocity, liftCoefficient, referenceArea = 1):
    downforce = -0.5 * airDensity * velocity**2 * referenceArea * liftCoefficient

    return downforce

# notice, only 3 arguements were give, because reference area will default to 1
downforce = CalculateDownforce(1.225, 20, -2.4)

# notice, we can also change the value of reference area if we want to
# it just defaults to 1 if we say nothing

# you should write referenceArea= the value you want, so its more clear when you have . . .
# . . . a case with multiple default arguments
downforce = CalculateDownforce(1.225, 20, -2.4, referenceArea= 2)



print(f"Downforce: {round(downforce, 2)} N")

print()


# Reusing a function with a loop
velocities = [10, 15, 20, 25, 30]

for velocity in velocities:
    downforce = CalculateDownforce(1.225, velocity, 1.5, -2.4)

    print(f"At {velocity} m/s, Downforce = {round(downforce, 2)} N")

### Classes

A **class** is a way of grouping related data and functions together into a single structure.

An **object** is an individual instance of a class. For example, we could create an `AeroSimulation` class and then create different simulation objects from it.

The `__init__()` function runs automatically when a new object is created and is used to set its initial values.

`self` refers to the specific object being used.

Variables stored inside an object are called **attributes**, while functions belonging to a class are called **methods**.

Classes become particularly useful as programs get larger, and we want to keep related data and functionality organised together.

> Classes also get very complex and have alot of compsci theory behind them since they are incredibly flexible, so this is just an intro so u can see what they are about when u see someone else's code.

In [73]:
class AeroSimulation:

    def __init__(self, velocity, liftCoefficient, dragCoefficient):
        self.velocity = velocity
        self.liftCoefficient = liftCoefficient
        self.dragCoefficient = dragCoefficient

    def PrintResults(self):
        print(f"Velocity: {self.velocity} m/s")
        print(f"Lift Coefficient: {self.liftCoefficient}")
        print(f"Drag Coefficient: {self.dragCoefficient}")


# Create an AeroSimulation object
ourSimulation = AeroSimulation(20, -2.4, 0.9)

# Access its attributes
print(ourSimulation.velocity)
print(ourSimulation.liftCoefficient)
print(ourSimulation.dragCoefficient)

print()


# Call a method belonging to the object
ourSimulation.PrintResults()

20
-2.4
0.9

Velocity: 20 m/s
Lift Coefficient: -2.4
Drag Coefficient: 0.9


### Fundamentals Challenge: Aero Parameter Sweep

Congratulations lol, You have now covered the main fundamentals of Python. This challenge will combine several of the concepts you have learned so far.

You are analysing the aerodynamic performance of a Formula Student car at different velocities.

Use the following values:

- Air density = **1.225 kg/m³**
- Reference area = **1.2 m²**
- Lift coefficient = **-2.5**
- Target downforce = **500 N**
- Velocities = **10, 15, 20, 25 and 30 m/s**

### Your Task

1. Store the velocities inside a **list**.

2. Create a function called `CalculateDownforce()` that:
   - Takes air density, velocity, lift coefficient and reference area as parameters.
      - have the code set a default parameter value for air density and for lift coefficient and Reference area
   - Calculates the downforce.
   - Returns the calculated value.

3. Use a **for loop** to calculate the downforce at every velocity in the list.

4. Print the velocity and calculated downforce for each calculation.

5. Use an **if/else statement** to check whether the calculated downforce has reached the target downforce.

6. For each velocity, print whether the target downforce has been reached.

Try to make your output clear and easy to read using f strings

### Extra Challenge: Use a Class

Rewrite your program using an `AeroSimulation` class.

Your class should:

- Store the air density, reference area and lift coefficient as attributes.
- Have a method called `CalculateDownforce()` that takes velocity as a parameter and returns the calculated downforce.
- Create an `AeroSimulation` object using the values given above.
- Use your object inside the `for` loop to calculate the downforce at each velocity.
- Continue to check whether the target downforce has been reached and print the results.

Your new program should produce the same results as the original program, but the aerodynamic data and calculations should now be organised using a class.

Try to complete both challenges using only the concepts covered in the fundamentals section.

## Section 2: Engineering libraries

Now that the Python fundamentals have been covered, we can begin using Python for engineering applications.

Python has a large collection of **modules** that provide additional tools and functionality. Rather than writing everything ourselves, we can import these modules and use the functions they provide.

In this section, we will focus on some of the most useful Python modules for aerodynamic performance and engineering:

- **NumPy** for numerical calculations and working with arrays.
- **Matplotlib** for plotting and visualising data.
- **Pandas** for working with and analysing datasets.

These tools will allow us to move from basic Python programs towards analysing aerodynamic data, processing simulation results and automating engineering calculations.

### NumPy

**NumPy** is a Python module designed for working with numbers and numerical data.

The main feature of NumPy is the **array**. effectively an upgraded list


A NumPy array is similar to the Python lists we have already used, but is designed specifically for numerical calculations.

NumPy arrays allow us to perform calculations on many values at once, without needing to manually loop through every value.

This makes NumPy particularly useful for engineering, where we often work with large sets of numerical data.

NumPy is normally imported using the shortened name `np`.

In [5]:
# an import is normally done at the very top of our file, or in jupyter the first cell,
# here it is in this cell to show u how to import
import numpy as np


# Normal Python list
velocitiesList = [10, 15, 20, 25, 30]
print(velocitiesList)

print()


# NumPy array
velocitiesArray = np.array([10, 15, 20, 25, 30])
print(velocitiesArray)

print()


# Multiplying a normal list
print(velocitiesList * 2)

# Multiplying a NumPy array
print(velocitiesArray * 2)
print("notice the difference in the above two outputs ^")
print()


# Mathematical operations can be applied to the entire array
print(velocitiesArray + 5)
print(velocitiesArray - 5)
print(velocitiesArray ** 2)
print(velocitiesArray / 2)


[10, 15, 20, 25, 30]

[10 15 20 25 30]

[10, 15, 20, 25, 30, 10, 15, 20, 25, 30]
[20 30 40 50 60]
notice the difference in the above two outputs ^

[15 20 25 30 35]
[ 5 10 15 20 25]
[100 225 400 625 900]
[ 5.   7.5 10.  12.5 15. ]


### Creating NumPy Arrays

There are several ways to create NumPy arrays depending on what values we need.

`np.array()` converts an existing list of values into a NumPy array.

`np.arange()` creates an array of evenly spaced values using a **start, stop and step size**. Like `range()`, the stop value is not included.

`np.linspace()` creates an array between a start and end value, but instead of specifying the step size, we specify the **number of values** we want.

`np.linspace()` is particularly useful in engineering when we want a specific number of evenly spaced points between two values.

In [6]:
# No import cos we already did that last cell

# Creating an array from a list
velocities = np.array([10, 15, 20, 25, 30])

print(velocities)

print()


# np.arange(start, stop, step)
velocities = np.arange(10, 31, 5)

print(velocities)

print()


# np.linspace(start, stop, numberOfValues)
velocities = np.linspace(10, 30, 5)

print(velocities)

print()


# Creating more closely spaced points
yawAngles = np.linspace(-10, 10, 9)

print(yawAngles)

[10 15 20 25 30]

[10 15 20 25 30]

[10. 15. 20. 25. 30.]

[-10.   -7.5  -5.   -2.5   0.    2.5   5.    7.5  10. ]
